### ISSUE TITLE
Questions about the `batch_conv2d_weight_backward_f` function

### ISSUE THREAD

**Issue by axzml** [sebgao/cTensor#3]
Thank you for the awesome code! 

I am little confused about the `batch_conv2d_weight_backward_f` function

[ctensor/operator.py: batch_conv2d_weight_backward_f](https://github.com/sebgao/cTensor/blob/77a5199d1b0cff9faaac9869713038be66910801/ctensor/operator.py#L73)

```python
def batch_conv2d_weight_backward_f(kernel, input, stride=(1, 1)):
    '''kernel is result tensor grad, input is original tensor'''
    B, C, H, W = kernel.shape
    x = im2bchwkl(input, kernel.shape[-2:], dilation=stride)
    return np.tensordot(x, kernel, [(0, 4, 5), (0, 2, 3)]).transpose(0, 3, 1, 2)*(1.0/(B*H*W))
```

1. Why is the argument `dilation`  of `im2bchwkl` set to `stride` ?

2. Is `*(1.0/(B*H*W))` necessary in the gradient of weights ? 

![image](https://user-images.githubusercontent.com/16320631/57929521-24663500-78e6-11e9-9b3f-85f7b1259dc5.png)

According to the above equation, it seems `np.tensordot(x, kernel, [(0, 4, 5), (0, 2, 3)]).transpose(0, 3, 1, 2)` can get the final results.

**Comment by sebgao** [comment]
Sorry for the late response.

1. The dilation is required in the backward process if the forward convolution is strided. And the dilation rate is equal to the stride rate in the backward. You can easily check the gradient form by backwarding stride 2 convolution by hand.

2. You are right. My fault here. I thought that the gradient should be normalized by the batch, height and weight of the input. It should be `np.tensordot(x, kernel, [(0, 4, 5), (0, 2, 3)]).transpose(0, 3, 1, 2)`. I will fix that. Thank you for correcting.

**Comment by axzml** [comment]
Thank you for the kind response :smiley:. 

After I draw the process of convolution，I finally find why the dilation is needed and the dilation rate is indeed equal to the stride rate.

By the way, I recommend two blogs useful for understanding the workflow of the convolution layer's backpropagation with stride. 

+ [Part 1: Backpropagation for Convolution with Strides](https://medium.com/@mayank.utexas/backpropagation-for-convolution-with-strides-8137e4fc2710) 
+ [Part 2: Backpropagation for Convolution with Strides](https://medium.com/@mayank.utexas/backpropagation-for-convolution-with-strides-fb2f2efc4faa)

Thanks again, your code helps me a lot.
