### ISSUE TITLE
why set dilation=stride when do backward in conv2d in im2bchwkl

### ISSUE THREAD

**Issue by caijh23** [sebgao/cTensor#4]
I guess because you transpose the tensor in forward but why not transpose again in backward?I can not understand what would happen dilation=2.It seems strange when the params of as_stride of numpy is in such a `situation.
`istrides = list(istrides+istrides[-2:])
    istrides[2] *= stride[0]
    istrides[3] *= stride[1]
    istrides[4] *= dilation[0]
    istrides[5] *= dilation[1]
    return np.lib.stride_tricks.as_strided(input,
                                           (isize[0], isize[1], H,
                                            W, ksize[0], ksize[1]),
                                           istrides,
                                           writeable=writeable,
                                           )`

**Comment by sebgao** [comment]
Sorry for the late reply.

Please refer to #3 and also the good material provided in https://github.com/sebgao/cTensor/issues/3#issuecomment-494404212.
